session_name: rwm
start_directory: /home/duclos/Documents/projects/langs/c/wm
windows:
  - window_name: readme
    panes:
      - nvim README.md
  - window_name: src
    panes:
      - nvim src/main.c
  - window_name: bash
    layout: even-horizontal
    panes:
      - clear && ls -l
      - nvim CMakeLists.txt
